spring:
  application:
    name: loans
  profiles:
    active: production
  h2:
    console:
      enabled: true
      path: /h2
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update

logging:
  level:
    org:
      springframework: info

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true


openapi:
  info:
    title: "Loans API description"
    description: "Endpoint for HeadOffice, Accounting Engine, Private Area"
    termsOfService: null
    contact:
      name: "Alexandr Kil"
      url: null
      email: "Alexander.Kill@gmail.com"
#    license: null
    version: "0.0.1"
#  externalDocs: null
  servers: null
  security: null
  tags: null
#  paths: null
#  components: null